version: 0.0
os: linux
files:
  - source: /
    destination: /www/
hooks:
  BeforeInstall:
    - location: instance-setup
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
