#!/bin/bash
# I want to make sure that the directory is clean and has nothing left over from
# previous deployments. The servers auto scale so the directory may or may not
# exist.
sudo /etc/init.d/nginx stop
echo 'manually stopped nginx' >> /var/log/codedeploy.log
PROC="nginx"
for p in $PROC
do
  ps cax | grep $p > /dev/null

  if [ $? -eq 0 ]; then
    echo "Process $p is running start_server."  >> /var/log/codedeploy.log
  else
    echo "Process $p is not running start_server."  >> /var/log/codedeploy.log
    #sudo /etc/init.d/nginx start
  fi
done

cd /home/ubuntu/www/ec2test
sudo npm install
echo 'npm installed in /home/ubuntu/www/ec2test' >> /var/log/codedeploy.log
pm2 stop all
echo 'manually stopped pm2' >> /var/log/codedeploy.log
pm2 describe 'Ec2 Script Test' > /dev/null
RUNNING=$?
if [ "${RUNNING}" -ne 0 ]; then
  echo 'pm2 fired command pm2startup.json' >> /var/log/codedeploy.log
  pm2 start pm2startup.json
else
  echo 'pm2 gracefully' >> /var/log/codedeploy.log
  pm2 gracefulReload all
fi
