#!/bin/bash
# I want to make sure that the directory is clean and has nothing left over from
# previous deployments. The servers auto scale so the directory may or may not
# exist.
isExistApp = pgrep nginx
if [[ -n  $isExistApp ]]; then
#if (( $(ps -ef | grep -v grep | grep nginx | wc -l) > 0 )) then
    echo 'Do not need to restart nginx server' >> /var/log/codedeploy.log
    #sudo /etc/init.d/nginx restart
else
    echo 'start nginx' >> /var/log/codedeploy.log
    sudo /etc/init.d/nginx start
fi

cd /home/ubuntu/www/ec2test
sudo npm install
echo 'installed npm installed' >> /var/log/codedeploy.log

echo 'start pm2' >> /var/log/codedeploy.log
pm2 describe 'Ec2 Script Test' > /dev/null
RUNNING=$?
echo 'Running pm2 $RUNNING' >> /var/log/codedeploy.log
if [ "${RUNNING}" -ne 0 ]; then
  echo 'pm2 fired command pm2startup.json' >> /var/log/codedeploy.log
  pm2 start pm2startup.json
else
  echo 'pm2 gracefully' >> /var/log/codedeploy.log
  pm2 gracefulReload all
fi

PROC="nginx pm2"
for p in $PROC
do
  ps cax | grep $p > /dev/null

  if [ $? -eq 0 ]; then
    echo "Process $p is running."
  else
    echo "Process $p is not running."
  fi
done
