#!/bin/bash
#isExistApp = `pgrep nginx`
#if [[ -n  $isExistApp ]]; then
#service=nginx
#isnginxRunning = ps cax | grep nginx > /dev/null
#if [ $isnginxRunning -eq 0 ]; then
#if (( $(ps -ef | grep -v grep | grep $service | wc -l) > 0 )) then
#ps cax | grep nginx > /dev/null
#if [ $? -eq 0 ]; then
#    echo "nginx is running from stop_server" >> /var/log/codedeploy.log
    #echo 'nginx server found at the time of stop server' >> /var/log/codedeploy.log
#    sudo /etc/init.d/nginx stop
#fi
echo "------------------------------"  >> /var/log/codedeploy.log
echo "Start process of stop_server."  >> /var/log/codedeploy.log
PROC="nginx"
for p in $PROC
do
  ps cax | grep $p > /dev/null

  if [ $? -eq 0 ]; then
    echo "Process $p is running."  >> /var/log/codedeploy.log
  else
    echo "Process $p is not running."  >> /var/log/codedeploy.log
  fi
done
echo "Etart process of stop_server."  >> /var/log/codedeploy.log
